Update id used in params
dmdhrumilmistry/MusicAPy pull request #6
Opened 2023-03-21 01:07 UTC by arsaboo

Fixes https://github.com/dmdhrumilmistry/MusicAPy/issues/5

Looks like the correct endpoint is:

https://www.jiosaavn.com/api.php?__call=content.getAlbumDetails&_format=json&cc=in&_marker=0%3F_marker%3D0&albumid=43600311

Notice, we need `albumid` and not `pids`.

2023-03-22 09:19 UTC, dmdhrumilmistry commented
@arsaboo Provide me some time to check whether PR is crashing other components or not. pids were being used by other components. Might be we can create a new identifier for albums and use it wherever required.

2023-03-22 13:05 UTC, arsaboo commented
See the endpoints indicated [here](https://github.com/cyberboysumanjay/JioSaavnAPI/blob/master/endpoints.py). 

album_details need `albumid` and song_details uses `pids`. This PR should fix it. I will wait for your testing as well.

2023-03-22 16:10 UTC, dmdhrumilmistry commented
> I manually tested this endpoint and it works: https://www.jiosaavn.com/api.php?__call=song.getDetails&cc=in&_marker=0%3F_marker%3D0&_format=json&pids=8_j3Tm9A
> 
> Thus, `get_song_details` should use `pids` and `get_album_details` should use `albumid`.

yes. that's correct. 
But we should also create a new type for album in `create_identifier` method, which can used along with other types: `link` and `id`.

2023-03-22 16:24 UTC, arsaboo commented
> > I manually tested this endpoint and it works: https://www.jiosaavn.com/api.php?__call=song.getDetails&cc=in&_marker=0%3F_marker%3D0&_format=json&pids=8_j3Tm9A
> > Thus, `get_song_details` should use `pids` and `get_album_details` should use `albumid`.
> 
> yes. that's correct. But we should also create a new type for album in `create_identifier` method, which can used along with other types: `link` and `id`.

That will be an extension, where we add different types. One for the id which is part of the URL and the other for the id returned in the JSON object. 

Irrespective, the current implementation is not working for `get_album_details` with `pids`. 

My recommendation will be to change `pids` to `albumid` for now. Then, we can add two different identifiers - `url_id` or `album_url_id` (maybe?) for the part of the URL and `albumid` that Saavn uses internally.

2023-03-22 17:12 UTC, dmdhrumilmistry requested changes

2023-03-22 17:12 UTC, dmdhrumilmistry commented on musicapy/saavn_api/services.py
> +        param = {'token' if is_by_link else 'albumid': identifier['value']}
Can you add a check here? like if user uses string then use `pids`, if its int then use `albumid`. It'll provide users functionality to use whatever they feel.

2023-03-22 17:38 UTC, arsaboo commented on musicapy/saavn_api/services.py
> +        param = {'token' if is_by_link else 'albumid': identifier['value']}
I can but I am not sure what `pids` are in the context of albums. From what I understand, `pids` are only relevant for songs. Can you provide an example for me to understand how `pids` will be used in the case of albums?

2023-03-22 17:45 UTC, arsaboo commented on musicapy/saavn_api/services.py
> +        param = {'token' if is_by_link else 'albumid': identifier['value']}
Consider the album - Tu Jhoothi Main Makkaar
URL: https://www.jiosaavn.com/album/tu-jhoothi-main-makkaar/Zk6,htMIngg_
albumid returned: [43600311](https://www.jiosaavn.com/api.php?__call=content.getAlbumDetails&_format=json&cc=in&_marker=0%3F_marker%3D0&albumid=43600311)
The only end point that works is: [albumid=43600311](https://www.jiosaavn.com/api.php?__call=content.getAlbumDetails&_format=json&cc=in&_marker=0%3F_marker%3D0&albumid=43600311)
None of these other endpoint work: `pid=Zk6,htMIngg_`, `pids=Zk6,htMIngg_`, `albumid=Zk6,htMIngg_`, `albumid=Zk6,htMIngg_`

2023-03-22 17:50 UTC, arsaboo commented on musicapy/saavn_api/services.py
> +        param = {'token' if is_by_link else 'albumid': identifier['value']}
On the other hand, for songs, `pids` work perfectly for songs. Consider, for example, the song: https://www.jiosaavn.com/song/daiyya-daiyya/SDcBAiBdDnI
The id returned is `8_j3Tm9A`
The endpoint: https://www.jiosaavn.com/api.php?__call=song.getDetails&cc=in&_marker=0%3F_marker%3D0&_format=json&pids=8_j3Tm9A works fine here.

2023-03-23 02:41 UTC, dmdhrumilmistry commented on musicapy/saavn_api/services.py
> +        param = {'token' if is_by_link else 'albumid': identifier['value']}
Yikes, i got confused between `pids` and `token`. I made a silly mistake while writing the code.

- If user wants to get song by link then we need to use `token`

https://www.jiosaavn.com/api.php?_format=json&_marker=0&ctx=web6dot0&__call=webapi.get&type=album&token=Zk6,htMIngg_

- If they want to use album id then we need to use `albumid` 

https://www.jiosaavn.com/api.php?_format=json&_marker=0&ctx=web6dot0&__call=content.getAlbumDetails&albumid=43600311

So while creating the project. I missed the small details and used `pids` instead of `albumid`. 

I also created a PR on my local machine for the fix but unfortunately couldn't push it to Github. also I remembered that I need to update `create_identifier` method.

2023-03-23 02:41 UTC, dmdhrumilmistry approved these changes

2023-03-23 02:41 UTC, merged